### ISSUE TITLE
multi-fast5 files

### ISSUE THREAD

**Issue by Psy-Fer** [dnonatar/Sequoia#1]
Hello,

Does this support multi-fast5 files or only single fast5 files?

Let's say I have a modified and un-modified dRNA (RNA002) sets of multi-fast5 files, how would I go about making those compatible with this tool?

Cheers,

**Comment by DayeaPark** [comment]
I also confused about the input file. When I run it with the test fast5 file and it worked. However, when I try with my file from dRNA (RNA002), it is not compatible. I tried to run it with single and multiple reads, but not works. It seems it cannot get the input signals. Could you please provide how to modify my input file to make it compatible to your system? 

Here is the error that I got. 

Traceback (most recent call last):
  File "/Users/dayeapark/Desktop/Sequoia/test1.py", line 24, in <module>
    signal_array = list(hf.get(signal_path))
  File "/Users/dayeapark/miniconda3/envs/Sequoia/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 664, in __iter__
    yield self[i]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/dayeapark/miniconda3/envs/Sequoia/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 710, in __getitem__
    return self._fast_reader.read(args)
  File "h5py/_selector.pyx", line 366, in h5py._selector.Reader.read
OSError: Can't read data (can't open directory: /Users/dayeapark/miniconda3/envs/Sequoia/lib/hdf5/plugin)
